about/urls.py
from django.urls import path
from .views import about

app_name = 'about'

urlpatterns = [
    path('about/', about, name='about'),
]

home/urls.py
from django.urls import path
from .views import home

app_name='home'
urlpatterns = [
    path('',home,name='home'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('home.urls')),
    path("", include('about.urls')),
    path("", include('sintactico.urls')),
]

sintactico/urls.py
from django.urls import path
from .views import sintactico

#app_name = 'sintactico'

urlpatterns = [
    path('sintactico/', sintactico, name="sintactico")
]

about/models.py
from django.db import models

# Create your models here.

home/models.py
from functools import _make_key
from django.db import models
from django.db.models.base import Model

# Create your models here.
class Paciente(models.Model):
    name = models.CharField( max_length=50)
    

    class Meta:
        verbose_name = ("Paciente")
        verbose_name_plural = ("Pacientes")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Paciente_detail", kwargs={"pk": self.pk})



class Tejido(models.Model):
    temperatura = models.FloatField()    
    color = models.FloatField()
    inflamacion = models.FloatField(verbose_name='inflamación')
    name = models.ForeignKey( Paciente, blank=True, null=True, verbose_name='nombre', on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Tejido")
        verbose_name_plural = ("Tejidos")

    def __str__(self):
        if self.name is not None:
            return str(self.temperatura)
        else:
            return str(self.temperatura)

    def get_absolute_url(self):
        return reverse("Tejido_detail", kwargs={"pk": self.pk})
    

sintactico/models.py
from django.db import models

# Create your models here.

about/views.py
from django.http import request
from django.shortcuts import render
from home import views
from home.models import Tejido

# Create your views here.
def about(request):
    L=Tejido.objects.get_queryset()
    mat = views.matrizDist(L)
    grafo=[]
    
    if request.method == "POST":
        grafo = procesaGrafo(mat,int(request.POST['valorUmbral']))


    template_name="about/about.html"
    return render(request,template_name,{"mat":mat,"grafo":grafo})

def procesaGrafo(matriz, umbral):
    grafo=[]
    comparadorDos = 1

    for lista in matriz:
        comparador = 1
        for valor in lista:

            if comparadorDos < comparador or comparadorDos==comparador:
                if valor > umbral:
                    grafo.append([str(comparadorDos)+"-"+str(comparador), 1])
                else:
                    grafo.append([str(comparadorDos)+"-"+str(comparador), 0])

            comparador += 1
        comparadorDos += 1

    return grafo

home/views.py
from django.shortcuts import render
from .models import Tejido

# Create your views here.

def home(request):
    L=Tejido.objects.get_queryset()  

    #listProcesada = procesaLista(L)

    matrizDat = matrizDist(L)
    diccionario = {'lista':L,'matrizDat':matrizDat,}
    template_name = "home/index.html"
    return render(request, template_name, diccionario)

def procesaLista(lista):
    lista1=[]
    for elemento in lista:
        valor = elemento.temperatura**2 + elemento.inflamacion**2 + elemento.color**2
        res = valor**0.5
        if res > 100:
            lista1.append(res)
    return lista1

def matrizDist(lista):
    tamaño = len(lista)
    matrizVacia = []
    contador = 0
    for i in range(tamaño):
        matrizVacia.append([0]*tamaño)
    for fila in matrizVacia:
        for columna in range(len(fila)):
            valorResultado = 0
            valorResultado = (lista[columna].temperatura - lista[contador].temperatura)**2+(lista[columna].color - lista[contador].color)**2+(lista[columna].inflamacion - lista[contador].inflamacion)**2
            formato = valorResultado**0.5
            matrizVacia[contador][columna] = round(formato,3)
        contador += 1
    return matrizVacia

sintactico/views.py
from django.shortcuts import render

# Create your views here.

def sintactico(request):
    template_name="sintactico/sintactico.html"
    return render(request, template_name, {})

about/templates/about/about.html
{% extends 'home/index.html' %}
{% load static %}

{% block contenido %}
<div class="container" id="about">
    <div class="Boton">

        <br>
        <h1>Generar Grafo</h1>

        <p>Ingresa el umbral para generar el grafo correspondiente</p>

        <form class="form-inline d-flex justify-content-center" method="POST" action="{% url 'about:about' %}">
            {% csrf_token %}
            <label for="exampleFormControlText" class="col-sm-3 col-form-label">Ingresa el valor del umbral</label>
            <input type="text" class="form-control mr-2" name="valorUmbral" placeholder="">
            <button type="submit" class="btn btn-primary">Procesar</button>
        </form>

    </div>
    <br>
    <div>
        <div class="container d-flex justify-content-center align-items-center tablaGrafo">
            <div class="alineaGrafo">
                <table class="table table-borderless table-dark">
                    <thead>
                        <tr>
                            <th>Relacion</th>
                            <th>Resultado</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for valorGraf in grafo %}
                        <tr>

                            {% for datoGraf in valorGraf%}
                            <td align="center">{{datoGraf}}</td>
                            {% endfor %}

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link type="text/css" href='{% static "css/index.css" %}' rel="stylesheet">
    <title>RSE Matutino</title>

</head>

<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navegacion">
            <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sintactico' %}">Informacion<span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about:about' %}">Grafo</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    {% block contenido %}
    <div class="container">
        <div id="infHome">
            <br>
            <h1>Cancer de prostata</h1>
            <p>
                El cáncer de próstata es el cáncer que se forma en la próstata. En los hombres, la próstata es una
                glándula pequeña con forma de nuez, que produce el líquido seminal que nutre y transporta el esperma.
            </p>
            <p>
                El cáncer de próstata es uno de los tipos más comunes de cáncer. Muchos cánceres de próstata crecen
                lentamente y permanecen limitados a la glándula prostática, en donde pueden no causar daño grave.
                Pero, si bien algunos tipos de cáncer de próstata crecen lentamente y pueden necesitar un tratamiento
                mínimo o no necesitar ningún tratamiento, otros tipos son agresivos y se pueden diseminar con rapidez.
            </p>
            <p>
                El cáncer de próstata que se detecta en forma temprana, cuando todavía está limitado a la glándula
                prostática,
                tiene mejores probabilidades de tener un tratamiento exitoso.
            </p>
            <div class="row">
                <div class="col-sm-7">
                    <h2>Síntomas</h2>

                    <p>El cáncer de próstata puede no provocar signos ni síntomas en sus primeros estudios.</p>
                    <p>El cáncer de próstata que está más avanzado puede causar signos y síntomas como:</p>

                    <li>Problemas para orinar
                    <li>Disminución en la fuerza del flujo de la orina
                    <li>Sangre en la orina
                    <li>Sangre en el semen
                    <li>Dolor de huesos
                    <li>Pérdida de peso sin intentarlo
                    <li>Disfunción eréctil
                </div>
                <div class="col-sm-5 d-flex justify-content-center align-items-center">
                    <img class="img-thumbnail mx-auto d-block"
                        src="https://biotechmagazineandnews.com/wp-content/uploads/2021/04/cancer-prostata.jpg"
                        alt="cancer-prostata-tumores">
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-5">
                <h2 align="center">Muestras</h2>
                <p>Se agrega una tabla de muestras sobre una base de datos del cancer de prostata, junto a una matriz de
                    distancias generadas entre cada registro</p>
                <div class="container d-flex justify-content-center align-items-center" id="tablaMuestras">
                    <div class="tablealing">
                        <table class="p-0 table table-borderless table-dark">

                            <thead>
                                <tr>
                                    <th scope="col">Clave</th>
                                    <th scope="col">Temperatura</th>
                                    <th scope="col">Color</th>
                                    <th scope="col">Inflamacion</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for elemento in lista %}

                                <tr>
                                    <th scope="row">{{elemento.pk}}</th>
                                    <td>{{elemento.temperatura}}</td>
                                    <td>{{elemento.color}}</td>
                                    <td>{{elemento.inflamacion}}</td>
                                </tr>

                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-sm-7">
                <h2 align="center">Matriz de Distancias</h2>
                <div class="container d-flex justify-content-center align-items-center" id="matriz">
                    <div class="matrizaling">
                        <table class="table table-borderless table-dark">
                            <tbody>
                                {% for valor in matrizDat %}
                                <tr>

                                    {% for dato in valor%}
                                    <td align="center">{{dato}}</td>
                                    {% endfor %}

                                </tr>
                                {% endfor %}
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock contenido %}

    <hr>
    <div class="container" id="piePagina">
        <div class="row">
            <div class="col-sm-8">
                <p>Proyecto Reconocimiento de Patrones Sintactico Estructural</p>
                <p>Contacto</p>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-2">
                                <div class="d-flex justify-content-center align-items-center">
                                    <img src="https://i.pinimg.com/originals/ce/c8/a6/cec8a6239de29acbfcfee0ccec995b9f.png"
                                        alt="boton-facebook"></i>
                                </div>
                                <p class="textAl">Facebook</p>
                            </div>
                            <div class="col-sm-2">
                                <div class="d-flex justify-content-center align-items-center">
                                    <img src="http://assets.stickpng.com/images/580b57fcd9996e24bc43c521.png"
                                        alt="boton-facebook"></i>
                                </div>
                                <p class="textAl">Instagram</p>
                            </div>
                            <div class="col-sm-2">
                                <div class="d-flex justify-content-center align-items-center">
                                    <img src="http://assets.stickpng.com/images/580b57fcd9996e24bc43c53e.png"
                                        alt="boton-facebook"></i>
                                </div>
                                <p class="textAl">Twitter</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <p>Proyecto realizado por: </p>
                <p>Viridiana Jimenez Pineda</p>
                <p>Raúl Alejandro Luis Carvarin</p>
                <p>Grupo "M9"</p>
            </div>
        </div>
    </div>

</body>

</html>

sintactico/templates/sintactico/sintactico.html
{% extends 'home/index.html' %}
{% load static %}

{% block contenido %}

<div class="container p-4" id="infoSintac">
    <div class="row">
        <div class="col-sm-7">
            <h2>Causas del Cancer de Prostata</h2>
            <p>
                Las causas del cáncer de próstata no son claras.
            </p>
            <p>
                Los médicos sabea que el cáncer de próstata comienza cuando las células en la próstata presentan cambios
                en el ADN.
                El ADN de la célula contiene las instrucciones que le dicen a la célula qué debe hacer. Los cambios
                instruyen a las
                células que crezcan y se dividan más rápidamente que las células normales. Las células anormales
                continúan viviendo
                cuando otras células morirían.
            </p>
            <p>
                La acumulación de células anormales forma un tumor que puede crecer e invadir el tejido cercano.
                Con el tiempo, algunas células anormales pueden desprenderse y esparcirse (hacer metástasis)
                hacia otras partes del cuerpo.
            </p>
        </div>
        <div class="col-sm-5 d-flex justify-content-center align-items-center">
            <img class="p-4" src="https://medlineplus.gov/spanish/ency/images/ency/fullsize/18038.jpg"
                alt="Cancer-Prostata" class="img-thumbnail mx-auto d-block">
        </div>
    </div>
    <div class="col-sm-10">
        <h2>Factores de riesgo</h2>
        <p>
            Los factores que pueden aumentar el riesgo de cáncer de próstata son los siguientes:
            <li>
                Edad avanzada. El riesgo de tener cáncer de próstata aumenta con la edad. Es más frecuente después de
                los 50
                años de edad.
            </li>
            <li>
                Raza. Por razones que aún no se han determinado, los hombres afroamericanos tienen un mayor riesgo de
                cáncer
                de próstata que los de otras razas. En los afroamericanos, el cáncer de próstata también tiene más
                probabilidades de ser agresivo o avanzado.
            </li>
            <li>
                Antecedentes familiares. Si se ha diagnosticado con cáncer de próstata a un familiar cercano, como un
                padre,
                hermano o hijo, quizás tu riesgo sea más alto. También, si tienes antecedentes familiares de genes que
                aumentan el riesgo para cáncer de mama (BRCA1 o BRCA2) o antecedentes familiares significativos de
                cáncer de
                mama, tu riesgo para cáncer de próstata quizás sea más alto.
            </li>
            <li>
                Obesidad. Las personas obesas quizás estén a un riesgo más alto de padecer cáncer de próstata,
                comparadas
                con las que se considera están a un peso saludable, aunque los estudios han producido resultados mixtos.
                En
                las personas obesas, es más probable que el cáncer sea más agresivo o o que recurra después del
                tratamiento
                inicial.
            </li>
        </p>
    </div>
    <div class="row">
        <div class="col-sm-7">
            <h2>Complicaciones</h2>
            <p>
                Las complicaciones del cáncer de próstata y sus tratamientos incluyen:
            </p>
            <li>
                Cáncer que se disemina (metástasis). El cáncer de próstata puede extenderse a órganos cercanos, como la
                vejiga, o diseminarse por el torrente sanguíneo o el sistema linfático hasta los huesos u otros órganos.
                El cáncer de próstata que se extiende a los huesos puede provocar dolor y fracturas. Una vez que el
                cáncer de próstata se extendió a otras zonas del cuerpo, todavía puede responder al tratamiento y puede
                controlarse, pero no es probable que se cure.
            </li>
            <li>
                Incontinencia. El cáncer de próstata y su tratamiento pueden causar incontinencia urinaria. El
                tratamiento para la incontinencia depende del tipo que tengas, la gravedad y la probabilidad de que
                mejore con el tiempo. Entre las opciones de tratamiento se encuentran los medicamentos, el sondaje y la
                cirugía.
            </li>
            <li>
                Disfunción eréctil. La disfunción eréctil puede resultar del cáncer de próstata o su tratamiento, por
                ejemplo, la cirugía, la radiación o los tratamientos con hormonas. Hay medicamentos, dispositivos de
                vacío que ayudan a lograr la erección y cirugías para tratar la disfunción eréctil.
            </li>
        </div>
        <div class="col-sm-5 p-2 d-flex justify-content-center align-items-center">
            <img src="https://urologiadealtaespecialidad.com/wp-content/uploads/2020/10/C%C3%A1ncer-de-pr%C3%B3stata-en-Quer%C3%A9taro.png"
                alt="cancer-prostata-complicaciones" class="img-thumbnail mx-auto d-block img-dolor">
        </div>
    </div>

</div>

{% endblock contenido %}